// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: management.proto

package managementproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignatureRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureRule) Reset() {
	*x = SignatureRule{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRule) ProtoMessage() {}

func (x *SignatureRule) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRule.ProtoReflect.Descriptor instead.
func (*SignatureRule) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *SignatureRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SignatureRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignatureRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SignatureRule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SignatureRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type SignatureBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	BundleVersion string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	PushedBy      string                 `protobuf:"bytes,3,opt,name=pushed_by,json=pushedBy,proto3" json:"pushed_by,omitempty"` // e.g. "pardus1"
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Rules         []*SignatureRule       `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	RawBundleData []byte                 `protobuf:"bytes,6,opt,name=raw_bundle_data,json=rawBundleData,proto3" json:"raw_bundle_data,omitempty"` // raw json or yaml payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureBundle) Reset() {
	*x = SignatureBundle{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureBundle) ProtoMessage() {}

func (x *SignatureBundle) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureBundle.ProtoReflect.Descriptor instead.
func (*SignatureBundle) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *SignatureBundle) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *SignatureBundle) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *SignatureBundle) GetPushedBy() string {
	if x != nil {
		return x.PushedBy
	}
	return ""
}

func (x *SignatureBundle) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *SignatureBundle) GetRules() []*SignatureRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SignatureBundle) GetRawBundleData() []byte {
	if x != nil {
		return x.RawBundleData
	}
	return nil
}

type PushSignaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RulesLoaded   uint32                 `protobuf:"varint,3,opt,name=rules_loaded,json=rulesLoaded,proto3" json:"rules_loaded,omitempty"`
	EngineVersion uint64                 `protobuf:"varint,4,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSignaturesResponse) Reset() {
	*x = PushSignaturesResponse{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSignaturesResponse) ProtoMessage() {}

func (x *PushSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSignaturesResponse.ProtoReflect.Descriptor instead.
func (*PushSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *PushSignaturesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushSignaturesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushSignaturesResponse) GetRulesLoaded() uint32 {
	if x != nil {
		return x.RulesLoaded
	}
	return 0
}

func (x *PushSignaturesResponse) GetEngineVersion() uint64 {
	if x != nil {
		return x.EngineVersion
	}
	return 0
}

func (x *PushSignaturesResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type EngineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineStatusRequest) Reset() {
	*x = EngineStatusRequest{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatusRequest) ProtoMessage() {}

func (x *EngineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatusRequest.ProtoReflect.Descriptor instead.
func (*EngineStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *EngineStatusRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type EngineStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActiveRulesCount    uint32                 `protobuf:"varint,1,opt,name=active_rules_count,json=activeRulesCount,proto3" json:"active_rules_count,omitempty"`
	EngineVersion       uint64                 `protobuf:"varint,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	LastSwapTimestampMs int64                  `protobuf:"varint,3,opt,name=last_swap_timestamp_ms,json=lastSwapTimestampMs,proto3" json:"last_swap_timestamp_ms,omitempty"`
	TotalSwaps          uint64                 `protobuf:"varint,4,opt,name=total_swaps,json=totalSwaps,proto3" json:"total_swaps,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EngineStatusResponse) Reset() {
	*x = EngineStatusResponse{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatusResponse) ProtoMessage() {}

func (x *EngineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatusResponse.ProtoReflect.Descriptor instead.
func (*EngineStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *EngineStatusResponse) GetActiveRulesCount() uint32 {
	if x != nil {
		return x.ActiveRulesCount
	}
	return 0
}

func (x *EngineStatusResponse) GetEngineVersion() uint64 {
	if x != nil {
		return x.EngineVersion
	}
	return 0
}

func (x *EngineStatusResponse) GetLastSwapTimestampMs() int64 {
	if x != nil {
		return x.LastSwapTimestampMs
	}
	return 0
}

func (x *EngineStatusResponse) GetTotalSwaps() uint64 {
	if x != nil {
		return x.TotalSwaps
	}
	return 0
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\x11copsec.management\"\x85\x01\n" +
	"\rSignatureRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"\xf5\x01\n" +
	"\x0fSignatureBundle\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\x12\x1b\n" +
	"\tpushed_by\x18\x03 \x01(\tR\bpushedBy\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x126\n" +
	"\x05rules\x18\x05 \x03(\v2 .copsec.management.SignatureRuleR\x05rules\x12&\n" +
	"\x0fraw_bundle_data\x18\x06 \x01(\fR\rrawBundleData\"\xb9\x01\n" +
	"\x16PushSignaturesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\frules_loaded\x18\x03 \x01(\rR\vrulesLoaded\x12%\n" +
	"\x0eengine_version\x18\x04 \x01(\x04R\rengineVersion\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"8\n" +
	"\x13EngineStatusRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"\xc1\x01\n" +
	"\x14EngineStatusResponse\x12,\n" +
	"\x12active_rules_count\x18\x01 \x01(\rR\x10activeRulesCount\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\x04R\rengineVersion\x123\n" +
	"\x16last_swap_timestamp_ms\x18\x03 \x01(\x03R\x13lastSwapTimestampMs\x12\x1f\n" +
	"\vtotal_swaps\x18\x04 \x01(\x04R\n" +
	"totalSwaps2\xde\x01\n" +
	"\x17SensorManagementService\x12_\n" +
	"\x0ePushSignatures\x12\".copsec.management.SignatureBundle\x1a).copsec.management.PushSignaturesResponse\x12b\n" +
	"\x0fGetEngineStatus\x12&.copsec.management.EngineStatusRequest\x1a'.copsec.management.EngineStatusResponseB>Z<github.com/copsec/collector/proto/management;managementprotob\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_management_proto_goTypes = []any{
	(*SignatureRule)(nil),          // 0: copsec.management.SignatureRule
	(*SignatureBundle)(nil),        // 1: copsec.management.SignatureBundle
	(*PushSignaturesResponse)(nil), // 2: copsec.management.PushSignaturesResponse
	(*EngineStatusRequest)(nil),    // 3: copsec.management.EngineStatusRequest
	(*EngineStatusResponse)(nil),   // 4: copsec.management.EngineStatusResponse
}
var file_management_proto_depIdxs = []int32{
	0, // 0: copsec.management.SignatureBundle.rules:type_name -> copsec.management.SignatureRule
	1, // 1: copsec.management.SensorManagementService.PushSignatures:input_type -> copsec.management.SignatureBundle
	3, // 2: copsec.management.SensorManagementService.GetEngineStatus:input_type -> copsec.management.EngineStatusRequest
	2, // 3: copsec.management.SensorManagementService.PushSignatures:output_type -> copsec.management.PushSignaturesResponse
	4, // 4: copsec.management.SensorManagementService.GetEngineStatus:output_type -> copsec.management.EngineStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
