// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: management.proto

package managementproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorManagementService_PushSignatures_FullMethodName  = "/copsec.management.SensorManagementService/PushSignatures"
	SensorManagementService_GetEngineStatus_FullMethodName = "/copsec.management.SensorManagementService/GetEngineStatus"
)

// SensorManagementServiceClient is the client API for SensorManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SensorManagementService provides dynamic remote administration of collector sensors.
type SensorManagementServiceClient interface {
	// PushSignatures atomically compiles and hot-swaps updated threat signature bundles.
	PushSignatures(ctx context.Context, in *SignatureBundle, opts ...grpc.CallOption) (*PushSignaturesResponse, error)
	// GetEngineStatus reports the active DFA ruleset metadata and swap metrics.
	GetEngineStatus(ctx context.Context, in *EngineStatusRequest, opts ...grpc.CallOption) (*EngineStatusResponse, error)
}

type sensorManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorManagementServiceClient(cc grpc.ClientConnInterface) SensorManagementServiceClient {
	return &sensorManagementServiceClient{cc}
}

func (c *sensorManagementServiceClient) PushSignatures(ctx context.Context, in *SignatureBundle, opts ...grpc.CallOption) (*PushSignaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushSignaturesResponse)
	err := c.cc.Invoke(ctx, SensorManagementService_PushSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorManagementServiceClient) GetEngineStatus(ctx context.Context, in *EngineStatusRequest, opts ...grpc.CallOption) (*EngineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EngineStatusResponse)
	err := c.cc.Invoke(ctx, SensorManagementService_GetEngineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorManagementServiceServer is the server API for SensorManagementService service.
// All implementations must embed UnimplementedSensorManagementServiceServer
// for forward compatibility.
//
// SensorManagementService provides dynamic remote administration of collector sensors.
type SensorManagementServiceServer interface {
	// PushSignatures atomically compiles and hot-swaps updated threat signature bundles.
	PushSignatures(context.Context, *SignatureBundle) (*PushSignaturesResponse, error)
	// GetEngineStatus reports the active DFA ruleset metadata and swap metrics.
	GetEngineStatus(context.Context, *EngineStatusRequest) (*EngineStatusResponse, error)
	mustEmbedUnimplementedSensorManagementServiceServer()
}

// UnimplementedSensorManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorManagementServiceServer struct{}

func (UnimplementedSensorManagementServiceServer) PushSignatures(context.Context, *SignatureBundle) (*PushSignaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushSignatures not implemented")
}
func (UnimplementedSensorManagementServiceServer) GetEngineStatus(context.Context, *EngineStatusRequest) (*EngineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEngineStatus not implemented")
}
func (UnimplementedSensorManagementServiceServer) mustEmbedUnimplementedSensorManagementServiceServer() {
}
func (UnimplementedSensorManagementServiceServer) testEmbeddedByValue() {}

// UnsafeSensorManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorManagementServiceServer will
// result in compilation errors.
type UnsafeSensorManagementServiceServer interface {
	mustEmbedUnimplementedSensorManagementServiceServer()
}

func RegisterSensorManagementServiceServer(s grpc.ServiceRegistrar, srv SensorManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedSensorManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorManagementService_ServiceDesc, srv)
}

func _SensorManagementService_PushSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignatureBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorManagementServiceServer).PushSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorManagementService_PushSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorManagementServiceServer).PushSignatures(ctx, req.(*SignatureBundle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorManagementService_GetEngineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EngineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorManagementServiceServer).GetEngineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorManagementService_GetEngineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorManagementServiceServer).GetEngineStatus(ctx, req.(*EngineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorManagementService_ServiceDesc is the grpc.ServiceDesc for SensorManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copsec.management.SensorManagementService",
	HandlerType: (*SensorManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushSignatures",
			Handler:    _SensorManagementService_PushSignatures_Handler,
		},
		{
			MethodName: "GetEngineStatus",
			Handler:    _SensorManagementService_GetEngineStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
