// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: copsec.proto

package copsecproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CopsecStreamService_StreamEvents_FullMethodName  = "/copsec.CopsecStreamService/StreamEvents"
	CopsecStreamService_SendHeartbeat_FullMethodName = "/copsec.CopsecStreamService/SendHeartbeat"
	CopsecStreamService_SyncCommands_FullMethodName  = "/copsec.CopsecStreamService/SyncCommands"
)

// CopsecStreamServiceClient is the client API for CopsecStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CopsecStreamService orchestrates bidirectional streaming between edge nodes and Controller
type CopsecStreamServiceClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, StreamAck], error)
	SendHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SyncCommands(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandAck, SOARCommand], error)
}

type copsecStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCopsecStreamServiceClient(cc grpc.ClientConnInterface) CopsecStreamServiceClient {
	return &copsecStreamServiceClient{cc}
}

func (c *copsecStreamServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CopsecStreamService_ServiceDesc.Streams[0], CopsecStreamService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEvent, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CopsecStreamService_StreamEventsClient = grpc.ClientStreamingClient[LogEvent, StreamAck]

func (c *copsecStreamServiceClient) SendHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CopsecStreamService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copsecStreamServiceClient) SyncCommands(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandAck, SOARCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CopsecStreamService_ServiceDesc.Streams[1], CopsecStreamService_SyncCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandAck, SOARCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CopsecStreamService_SyncCommandsClient = grpc.BidiStreamingClient[CommandAck, SOARCommand]

// CopsecStreamServiceServer is the server API for CopsecStreamService service.
// All implementations must embed UnimplementedCopsecStreamServiceServer
// for forward compatibility.
//
// CopsecStreamService orchestrates bidirectional streaming between edge nodes and Controller
type CopsecStreamServiceServer interface {
	StreamEvents(grpc.ClientStreamingServer[LogEvent, StreamAck]) error
	SendHeartbeat(context.Context, *Heartbeat) (*HeartbeatResponse, error)
	SyncCommands(grpc.BidiStreamingServer[CommandAck, SOARCommand]) error
	mustEmbedUnimplementedCopsecStreamServiceServer()
}

// UnimplementedCopsecStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopsecStreamServiceServer struct{}

func (UnimplementedCopsecStreamServiceServer) StreamEvents(grpc.ClientStreamingServer[LogEvent, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedCopsecStreamServiceServer) SendHeartbeat(context.Context, *Heartbeat) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedCopsecStreamServiceServer) SyncCommands(grpc.BidiStreamingServer[CommandAck, SOARCommand]) error {
	return status.Error(codes.Unimplemented, "method SyncCommands not implemented")
}
func (UnimplementedCopsecStreamServiceServer) mustEmbedUnimplementedCopsecStreamServiceServer() {}
func (UnimplementedCopsecStreamServiceServer) testEmbeddedByValue()                             {}

// UnsafeCopsecStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopsecStreamServiceServer will
// result in compilation errors.
type UnsafeCopsecStreamServiceServer interface {
	mustEmbedUnimplementedCopsecStreamServiceServer()
}

func RegisterCopsecStreamServiceServer(s grpc.ServiceRegistrar, srv CopsecStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedCopsecStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CopsecStreamService_ServiceDesc, srv)
}

func _CopsecStreamService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CopsecStreamServiceServer).StreamEvents(&grpc.GenericServerStream[LogEvent, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CopsecStreamService_StreamEventsServer = grpc.ClientStreamingServer[LogEvent, StreamAck]

func _CopsecStreamService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopsecStreamServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopsecStreamService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopsecStreamServiceServer).SendHeartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopsecStreamService_SyncCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CopsecStreamServiceServer).SyncCommands(&grpc.GenericServerStream[CommandAck, SOARCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CopsecStreamService_SyncCommandsServer = grpc.BidiStreamingServer[CommandAck, SOARCommand]

// CopsecStreamService_ServiceDesc is the grpc.ServiceDesc for CopsecStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CopsecStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copsec.CopsecStreamService",
	HandlerType: (*CopsecStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _CopsecStreamService_SendHeartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _CopsecStreamService_StreamEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncCommands",
			Handler:       _CopsecStreamService_SyncCommands_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "copsec.proto",
}
