// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: copsec.proto

package copsecproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEvent represents an enriched, pre-filtered log security incident
type LogEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Source           string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // "nginx", "ssh", "syslog"
	RawLine          string                 `protobuf:"bytes,3,opt,name=raw_line,json=rawLine,proto3" json:"raw_line,omitempty"`
	ClientIp         string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	StatusCode       int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	TimestampMs      int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	RuleId           string                 `protobuf:"bytes,7,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	MitreTechniqueId string                 `protobuf:"bytes,8,opt,name=mitre_technique_id,json=mitreTechniqueId,proto3" json:"mitre_technique_id,omitempty"`
	ThreatScore      int32                  `protobuf:"varint,9,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_copsec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEvent) GetRawLine() string {
	if x != nil {
		return x.RawLine
	}
	return ""
}

func (x *LogEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEvent) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *LogEvent) GetMitreTechniqueId() string {
	if x != nil {
		return x.MitreTechniqueId
	}
	return ""
}

func (x *LogEvent) GetThreatScore() int32 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

// StreamAck confirms log batch delivery and reception
type StreamAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProcessedCount uint64                 `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_copsec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamAck) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *StreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat delivers agent telemetry and resource consumption
type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveBansCount int32                  `protobuf:"varint,5,opt,name=active_bans_count,json=activeBansCount,proto3" json:"active_bans_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_copsec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Heartbeat) GetActiveBansCount() int32 {
	if x != nil {
		return x.ActiveBansCount
	}
	return 0
}

// HeartbeatResponse contains acknowledgments and controller instructions
type HeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged        bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	SyncIntervalSeconds int32                  `protobuf:"varint,2,opt,name=sync_interval_seconds,json=syncIntervalSeconds,proto3" json:"sync_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_copsec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetSyncIntervalSeconds() int32 {
	if x != nil {
		return x.SyncIntervalSeconds
	}
	return 0
}

// SOARCommand is a proactive response directive dispatched from the central controller
type SOARCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ActionType      string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // "BAN_IP", "UNBAN_IP", "FLUSH_BANS"
	TargetIp        string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SOARCommand) Reset() {
	*x = SOARCommand{}
	mi := &file_copsec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOARCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOARCommand) ProtoMessage() {}

func (x *SOARCommand) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOARCommand.ProtoReflect.Descriptor instead.
func (*SOARCommand) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{4}
}

func (x *SOARCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SOARCommand) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *SOARCommand) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *SOARCommand) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// CommandAck confirms execution status of a SOARCommand on the edge node
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_copsec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_copsec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_copsec_proto_rawDescGZIP(), []int{5}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandAck) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_copsec_proto protoreflect.FileDescriptor

const file_copsec_proto_rawDesc = "" +
	"\n" +
	"\fcopsec.proto\x12\x06copsec\"\xa1\x02\n" +
	"\bLogEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x19\n" +
	"\braw_line\x18\x03 \x01(\tR\arawLine\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12\x17\n" +
	"\arule_id\x18\a \x01(\tR\x06ruleId\x12,\n" +
	"\x12mitre_technique_id\x18\b \x01(\tR\x10mitreTechniqueId\x12!\n" +
	"\fthreat_score\x18\t \x01(\x05R\vthreatScore\"h\n" +
	"\tStreamAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x04R\x0eprocessedCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb7\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12*\n" +
	"\x11active_bans_count\x18\x05 \x01(\x05R\x0factiveBansCount\"k\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x122\n" +
	"\x15sync_interval_seconds\x18\x02 \x01(\x05R\x13syncIntervalSeconds\"\x95\x01\n" +
	"\vSOARCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\"\x80\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs2\xc8\x01\n" +
	"\x13CopsecStreamService\x125\n" +
	"\fStreamEvents\x12\x10.copsec.LogEvent\x1a\x11.copsec.StreamAck(\x01\x12=\n" +
	"\rSendHeartbeat\x12\x11.copsec.Heartbeat\x1a\x19.copsec.HeartbeatResponse\x12;\n" +
	"\fSyncCommands\x12\x12.copsec.CommandAck\x1a\x13.copsec.SOARCommand(\x010\x01B/Z-github.com/copsec/collector/proto;copsecprotob\x06proto3"

var (
	file_copsec_proto_rawDescOnce sync.Once
	file_copsec_proto_rawDescData []byte
)

func file_copsec_proto_rawDescGZIP() []byte {
	file_copsec_proto_rawDescOnce.Do(func() {
		file_copsec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copsec_proto_rawDesc), len(file_copsec_proto_rawDesc)))
	})
	return file_copsec_proto_rawDescData
}

var file_copsec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_copsec_proto_goTypes = []any{
	(*LogEvent)(nil),          // 0: copsec.LogEvent
	(*StreamAck)(nil),         // 1: copsec.StreamAck
	(*Heartbeat)(nil),         // 2: copsec.Heartbeat
	(*HeartbeatResponse)(nil), // 3: copsec.HeartbeatResponse
	(*SOARCommand)(nil),       // 4: copsec.SOARCommand
	(*CommandAck)(nil),        // 5: copsec.CommandAck
}
var file_copsec_proto_depIdxs = []int32{
	0, // 0: copsec.CopsecStreamService.StreamEvents:input_type -> copsec.LogEvent
	2, // 1: copsec.CopsecStreamService.SendHeartbeat:input_type -> copsec.Heartbeat
	5, // 2: copsec.CopsecStreamService.SyncCommands:input_type -> copsec.CommandAck
	1, // 3: copsec.CopsecStreamService.StreamEvents:output_type -> copsec.StreamAck
	3, // 4: copsec.CopsecStreamService.SendHeartbeat:output_type -> copsec.HeartbeatResponse
	4, // 5: copsec.CopsecStreamService.SyncCommands:output_type -> copsec.SOARCommand
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_copsec_proto_init() }
func file_copsec_proto_init() {
	if File_copsec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copsec_proto_rawDesc), len(file_copsec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copsec_proto_goTypes,
		DependencyIndexes: file_copsec_proto_depIdxs,
		MessageInfos:      file_copsec_proto_msgTypes,
	}.Build()
	File_copsec_proto = out.File
	file_copsec_proto_goTypes = nil
	file_copsec_proto_depIdxs = nil
}
