// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: fleet.proto

package fleetproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerCommand_Type int32

const (
	ControllerCommand_COMMAND_HEARTBEAT_ACK  ControllerCommand_Type = 0
	ControllerCommand_COMMAND_ENFORCE_BAN    ControllerCommand_Type = 1
	ControllerCommand_COMMAND_REVOKE_BAN     ControllerCommand_Type = 2
	ControllerCommand_COMMAND_SYNC_WHITELIST ControllerCommand_Type = 3
)

// Enum value maps for ControllerCommand_Type.
var (
	ControllerCommand_Type_name = map[int32]string{
		0: "COMMAND_HEARTBEAT_ACK",
		1: "COMMAND_ENFORCE_BAN",
		2: "COMMAND_REVOKE_BAN",
		3: "COMMAND_SYNC_WHITELIST",
	}
	ControllerCommand_Type_value = map[string]int32{
		"COMMAND_HEARTBEAT_ACK":  0,
		"COMMAND_ENFORCE_BAN":    1,
		"COMMAND_REVOKE_BAN":     2,
		"COMMAND_SYNC_WHITELIST": 3,
	}
)

func (x ControllerCommand_Type) Enum() *ControllerCommand_Type {
	p := new(ControllerCommand_Type)
	*p = x
	return p
}

func (x ControllerCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[0].Descriptor()
}

func (ControllerCommand_Type) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[0]
}

func (x ControllerCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerCommand_Type.Descriptor instead.
func (ControllerCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2, 0}
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Health        *AgentHealth           `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMessage) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentMessage) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AgentMessage) GetHealth() *AgentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type AgentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveBans    int32                  `protobuf:"varint,3,opt,name=active_bans,json=activeBans,proto3" json:"active_bans,omitempty"`
	UptimeSec     int64                  `protobuf:"varint,4,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHealth) Reset() {
	*x = AgentHealth{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHealth) ProtoMessage() {}

func (x *AgentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHealth.ProtoReflect.Descriptor instead.
func (*AgentHealth) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentHealth) GetActiveBans() int32 {
	if x != nil {
		return x.ActiveBans
	}
	return 0
}

func (x *AgentHealth) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

type ControllerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          ControllerCommand_Type `protobuf:"varint,2,opt,name=type,proto3,enum=copsec.fleet.ControllerCommand_Type" json:"type,omitempty"`
	TargetIp      string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationSec   int64                  `protobuf:"varint,5,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerCommand) Reset() {
	*x = ControllerCommand{}
	mi := &file_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerCommand) ProtoMessage() {}

func (x *ControllerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerCommand.ProtoReflect.Descriptor instead.
func (*ControllerCommand) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ControllerCommand) GetType() ControllerCommand_Type {
	if x != nil {
		return x.Type
	}
	return ControllerCommand_COMMAND_HEARTBEAT_ACK
}

func (x *ControllerCommand) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *ControllerCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ControllerCommand) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *ControllerCommand) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RawEvents     [][]byte               `protobuf:"bytes,2,rep,name=raw_events,json=rawEvents,proto3" json:"raw_events,omitempty"`
	BatchId       int64                  `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryBatch) GetRawEvents() [][]byte {
	if x != nil {
		return x.RawEvents
	}
	return nil
}

func (x *TelemetryBatch) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       int64                  `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *StreamAck) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *StreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\fcopsec.fleet\"\xb8\x01\n" +
	"\fAgentMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x121\n" +
	"\x06health\x18\x05 \x01(\v2\x19.copsec.fleet.AgentHealthR\x06health\"\x8d\x01\n" +
	"\vAgentHealth\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1f\n" +
	"\vactive_bans\x18\x03 \x01(\x05R\n" +
	"activeBans\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x04 \x01(\x03R\tuptimeSec\"\xd7\x02\n" +
	"\x11ControllerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.copsec.fleet.ControllerCommand.TypeR\x04type\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\fduration_sec\x18\x05 \x01(\x03R\vdurationSec\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"n\n" +
	"\x04Type\x12\x19\n" +
	"\x15COMMAND_HEARTBEAT_ACK\x10\x00\x12\x17\n" +
	"\x13COMMAND_ENFORCE_BAN\x10\x01\x12\x16\n" +
	"\x12COMMAND_REVOKE_BAN\x10\x02\x12\x1a\n" +
	"\x16COMMAND_SYNC_WHITELIST\x10\x03\"c\n" +
	"\x0eTelemetryBatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"raw_events\x18\x02 \x03(\fR\trawEvents\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\x03R\abatchId\"@\n" +
	"\tStreamAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x03R\abatchId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xab\x01\n" +
	"\fFleetService\x12O\n" +
	"\fConnectFleet\x12\x1a.copsec.fleet.AgentMessage\x1a\x1f.copsec.fleet.ControllerCommand(\x010\x01\x12J\n" +
	"\x0fStreamTelemetry\x12\x1c.copsec.fleet.TelemetryBatch\x1a\x17.copsec.fleet.StreamAck(\x01B*Z(github.com/copsec/proto/fleet;fleetprotob\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleet_proto_goTypes = []any{
	(ControllerCommand_Type)(0), // 0: copsec.fleet.ControllerCommand.Type
	(*AgentMessage)(nil),        // 1: copsec.fleet.AgentMessage
	(*AgentHealth)(nil),         // 2: copsec.fleet.AgentHealth
	(*ControllerCommand)(nil),   // 3: copsec.fleet.ControllerCommand
	(*TelemetryBatch)(nil),      // 4: copsec.fleet.TelemetryBatch
	(*StreamAck)(nil),           // 5: copsec.fleet.StreamAck
}
var file_fleet_proto_depIdxs = []int32{
	2, // 0: copsec.fleet.AgentMessage.health:type_name -> copsec.fleet.AgentHealth
	0, // 1: copsec.fleet.ControllerCommand.type:type_name -> copsec.fleet.ControllerCommand.Type
	1, // 2: copsec.fleet.FleetService.ConnectFleet:input_type -> copsec.fleet.AgentMessage
	4, // 3: copsec.fleet.FleetService.StreamTelemetry:input_type -> copsec.fleet.TelemetryBatch
	3, // 4: copsec.fleet.FleetService.ConnectFleet:output_type -> copsec.fleet.ControllerCommand
	5, // 5: copsec.fleet.FleetService.StreamTelemetry:output_type -> copsec.fleet.StreamAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		EnumInfos:         file_fleet_proto_enumTypes,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
